### PR TITLE
simplify grab_residuals

### LINKED ISSUE #270: Checking whether grab_residuals method exists eating up unreasonable amounts of time
@dajmcdon as requested. Raised in relation to discussing https://github.com/cmu-delphi/exploration-tooling/issues/60. It appears that the `utils::methods` function [here](https://github.com/cmu-delphi/epipredict/blob/378577a213aa59043dea73e8fdea725432f32f16/R/layer_residual_quantiles.R#L138) is taking 9s out of 90s for running epipredict inside `epix_slide`, which was surprisingly long.

### PR DESCRIPTION
**Pull request by dajmcdon**
closes #270 .

### CODE REVIEW

**Review by dsweber2 — APPROVED** [review]
oh, it returns `NULL` if there aren't residuals? that does make this way easier. I'm assuming there's at least one non-regression model calling grab_residuals somewhere in the tests?

**Comment by dajmcdon** [comment]
I kind of doubt that there is a test where a classifier calls this function. Are you thinking that there needs to be?

**Comment by dshemetov** [comment]
Can we bump minor/patch version and add a note to CHANGELOG?

**Comment by dajmcdon** [comment]
@dshemetov Sure, though I'm unfamiliar. What would you like to bump to? 0.0.7 or 0.0.6001? Something else?

**Comment by dshemetov** [comment]
0.0.7 sounds good to me.

**Comment by dshemetov** [comment]
[This](https://usethis.r-lib.org/reference/use_version.html) might do it for you (haven't tried).

**Comment by dajmcdon** [comment]
residuals are just the difference between the training response and the point prediction (at least the kind we're using here), so would be mathematically defined for any regression engine (including quantile regression). This should fail if the engine is a classifier though.

**Pull request merged**
