### PR TITLE
feat: canned forecasters print their args by default

### LINKED ISSUE #309: Print the arguments used by a canned forecaster by default
There are many hidden arguments/parameters set by default in a canned forecaster. We should print these by default and add a `.verbose` option to suppress this print.

### PR DESCRIPTION
**Pull request by dshemetov**
### Checklist

Please:

-   [x] Make sure this PR is against "dev", not "main".
-   [x] Request a review from one of the current epipredict main reviewers:
        dajmcdon.
-   [ ] ~~Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
        Always increment the patch version number (the third number), unless you are
        making a release PR from dev to main, in which case increment the minor
        version number (the second number).~~
-   [x] Describe changes made in NEWS.md, making sure breaking changes
        (backwards-incompatible changes to the documented interface) are noted.
        Collect the changes under the next release number (e.g. if you are on
        0.7.2, then write your changes under the 0.8 heading).

### Change explanations for reviewer

Adds `.verbose = TRUE` to canned forecasters and prints their arguments if TRUE.

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

-   Resolves #309

### CODE REVIEW

**Review by dajmcdon — COMMENTED** [review]
Two comments:
1. I'd prefer this to be FALSE by default. I don't think functions should print stuff unless asked. It's potentially useful for debugging purposes, but otherwise the documentation (and, in this case, the function defaults) should be clear enough.
2. Should it be in the workflow creator? Or just in the forecaster? I can see arguments both ways. Another option is to set the default to TRUE in the workflow creator (a more developer-facing function) while it's FALSE in the forecaster (typical user-facing).

**Comment by dshemetov** [comment]
1. I think I leaned to the noisy default because I figured this is most useful for a beginner user of this package and I didn't want them to have to hunt for this flag. The more experienced users can turn it off and write a default-off wrapper for themselves if the extra typing is really bothering them.
2. My thinking was that both functions are user-facing, the workflow creator is just for a more advanced user. If that's true, I could see defaulting to off in the workflow creator and on in the simpler one.

**Comment by dajmcdon** [comment]
In R, I don't think it's customary to print things by default (with the possible exception of a progress bar, though even that is usually silent). I'd prefer these to be off. 

Come to think of it, I think we should add these to the print methods for the resulting object rather than altering the function signature at all.

**Comment by dshemetov** [comment]
I hear ya about not wanting to be too noisy. 

I like the idea of adding this to the object printer. Let me see what I can do there.

**Comment by dshemetov** [comment]
After thinking about it some more, doesn't seem worth it.

**Pull request closed without merging**
