### PR TITLE
feat: add snaphot tests of canned forecasters

### LINKED ISSUE #306: Add canned forecaster snapshot tests
Snapshot testing is useful when making refactoring changes, since it helps you fix the outputs of your code and makes sure it doesn't drift when you don't want it to. The {testthat} library provides convenient ways to snapshot using [expect_snapshot](https://testthat.r-lib.org/reference/expect_snapshot.html). I'd like to add and make sure we have a few snapshots for our canned forecasters.

### PR DESCRIPTION
**Pull request by dshemetov**
### Checklist

Please:

-   [x] Make sure this PR is against "dev", not "main".
-   [x] Request a review from one of the current epipredict main reviewers:
        dajmcdon.
-   [ ] ~~Makes sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
        Always increment the patch version number (the third number), unless you are
        making a release PR from dev to main, in which case increment the minor
        version number (the second number).~~
-   [ ] ~~Describe changes made in NEWS.md, making sure breaking changes
        (backwards-incompatible changes to the documented interface) are noted.
        Collect the changes under the next release number (e.g. if you are on
        0.7.2, then write your changes under the 0.8 heading).~~

### Change explanations for reviewer

Adds snapshot tests. Could add more snapshots with different parameter settings, but I went with a few for now.

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

-   Resolves #306

### CODE REVIEW

**Comment by dshemetov** [comment]
Ran into an issue where the CI and my local snapshots disagreed. Ran `renv::update()` locally, updated packages, and it seemed to fix it. Too many packages update to isolate the change, but this is a note for the future, in case others run into similar CI issues.

**Review by dajmcdon — APPROVED** [review]
I'm not entirely sure what impact this has, but maybe you can explain before merging?

**Comment by dshemetov** [comment]
So for each of our canned forecasters, I included the forecast outputs of a few (~default) forecaster (using included JHU data) as snapshots in the tests. Now these tests will compare the output of those forecasts on developer branches and will give us (at least some) confidence that internal changes have not altered these forecaster outputs. And if they have changed, you can run `testthat::snapshot_review()` to get a nice diff interface, where you can decide whether to accept or reject the new snapshots.

**Comment by dajmcdon** [comment]
Cool! And it runs on R CMD Check?

**Comment by dshemetov** [comment]
Yup, it's part of the tests, so it runs with `devtools::test()` too.

**Pull request merged**
