### PR TITLE
fix default slide values

### PR DESCRIPTION
**Pull request by dsweber2**
### Checklist

Please:

- [X] Make sure this PR is against "dev", not "main".
- [X] Request a review from one of the current epipredict main reviewers:
      dajmcdon.
- [ ] Make sure to bump the version number in `DESCRIPTION` and `NEWS.md`.
      Always increment the patch version number (the third number), unless you are
      making a release PR from dev to main, in which case increment the minor
      version number (the second number).
- [ ] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      0.7.2, then write your changes under the 0.8 heading).
- [X] Consider pinning the `epiprocess` version in the `DESCRIPTION` file if
  - You anticipate breaking changes in `epiprocess` soon
  - You want to co-develop features in `epipredict` and `epiprocess`

### Change explanations for reviewer

The actual defaults for `epi_slide` for `before` and `after` are `NULL`, so defaulting to `0` here breaks in the case of e.g. weekly data. For an example, see the test.

### CODE REVIEW

**Comment by dajmcdon** [comment]
@dsweber2 Can this be closed in light of #386 ?

**Comment by dsweber2** [comment]
looks like it

**Comment by dsweber2** [comment]
might be worth keeping to have a test of weekly, though probably easier to start from scratch

**Comment by dajmcdon** [comment]
Agreed. Let's rebase this on `dev` after #386 (changes the args to `step_epi_slide` anyway), then add a test for weekly.

**Comment by dshemetov** [comment]
This should raise an error if .window_size = NULL because epi_slide already does

**Pull request closed without merging**
