### PR TITLE
Modified `get_test_data()` to omit excess rows when lag != 0

### PR DESCRIPTION
**Pull request by rachlobay**
Addresses Issue #199 (modified `get_test_data()` function + added a test). Basically, omitted the end rows according to the min # of lags in the recipe when that's not 0.

### CODE REVIEW

**Review by dajmcdon — CHANGES_REQUESTED** [review]
I'm not yet convinced that this works. Can you add a test to make sure that we're getting the correct values? I'm actually not entirely sure what the right answer is here. Suppose I want to predict 3 days ahead with lags 2 and 4. My data are `1:10` with 10 being the most recent observation. Then I should use 8 and 6 as my `x` right? Is that what you get?

**Comment by rachlobay** [comment]
Ok. We could map your ex. onto the current test & look at the results:

```
ca <- case_death_rate_subset %>%
  filter(geo_value == "ca") %>% 
  slice_tail(n = 10)

rec <- epi_recipe(ca) %>%
  step_epi_lag(case_rate, lag = c(2, 4)) %>% # Expect these to be 63.7, 48.4, respectively, according to the case_rate values in rows 8, 6 of ca
  step_epi_ahead(case_rate, ahead = 3) %>% 
  step_epi_naomit()

td <- get_test_data(rec, ca)

bake(prep(rec, ca), td)
```

Output:

```
# A tibble: 1 × 7
  time_value geo_value case_rate death_rate lag_2_case_rate lag_4_case_rate ahead_3_case_rate
  <date>     <chr>         <dbl>      <dbl>           <dbl>           <dbl>             <dbl>
1 2021-12-31 ca               NA         NA            63.7            48.4                NA
```

I've added checks to ensure that the lags match the values in the original data for a similar example... Is this along the lines of what you want me to check into or is there something else you had in mind?

**Comment by dajmcdon** [comment]
Yes, exactly. But can you make it as simple as possible? Just create a minimal epi_df with obvious values that are easy to track.

**Comment by rachlobay** [comment]
Added a simpler ex. to the get_test_data() tests based on the situation you suggested above.
Ex. Set-up:
```
  toy_epi_df <- tibble::tibble(
    time_value = seq(as.Date("2020-01-01"), by = 1,
                     length.out = 10),
    geo_value = "ak",
    x = 1:10
  ) %>% epiprocess::as_epi_df()

  toy_rec <- epi_recipe(toy_epi_df) %>%
    step_epi_lag(x, lag = c(2, 4)) %>%
    step_epi_ahead(x, ahead = 3) %>%
    step_epi_naomit()

```

**Comment by rachlobay** [comment]
Also, this looks to address #209, so I added that to the development.

**Review by dajmcdon — APPROVED** [review]

**Pull request merged**
